### PR TITLE
fix: Adding missing service UUID for Lovense Osci

### PR DESCRIPTION
**Pull request by blackspherefollower**
fixes: #137

Tested with npm link'ed playground

### CODE REVIEW

**Comment by mathemagie** [comment]
> fixes: #137
> 
> Tested with npm link'ed playground

hi, 

first of all, tks for the fix 

how can I test the osci on my glitch project https://ossified-product.glitch.me/ , which online library should I include for this? instead of this one  

https://cdn.jsdelivr.net/npm/buttplug@0.8.0/dist/web/buttplug.min.js

**Comment by blackspherefollower** [comment]
> how can I test the osci on my glitch project https://ossified-product.glitch.me/ , which online library should I include for this?

Good question. I can't find a way to get the PR build's artifacts out of TravisCI.
I know @qdot is going to be swamped this week, so the best option might be to pull down the PR, do a local build and upload the resultant buttplug.min.js into your glitch project.

```
npm install
npm run build:all
```

**Comment by mathemagie** [comment]
> I know @qdot is going to be swamped this week, so the best option might be to pull down the PR, do a local build and upload the resultant buttplug.min.js into your glitch project.

Thank you, I'm doing it now. :)

**Comment by mathemagie** [comment]
> > I know @qdot is going to be swamped this week, so the best option might be to pull down the PR, do a local build and upload the resultant buttplug.min.js into your glitch project.
> 
> Thank you, I'm doing it now. :)

with your patch, it's working fine on my glitch project https://ossified-product.glitch.me/ :)

**Comment by qdot** [comment]
Ok I'll get this integrated soon. Thanks for testing!

**Comment by qdot** [comment]
Landed as 1319b457c146b6aad0101776c23e2fefa6334d64 but didn't resolve to the PR for some reason. Released in 0.8.3.

**Pull request closed without merging**
